### ISSUE TITLE
Runtime errors on 2d arrays

### ISSUE THREAD

**Issue by tristanlmiller** [mwburke/population-stability-index#1]
I was unable to run this function on 2d arrays.  I believe I've identified the problem, in line 72:
```psi_values = np.empty(expected.shape[axis])```
should be changed to 
```psi_values = np.empty(expected.shape[1-axis])```

Basically, when declaring the size of the output, it uses the wrong axis of the input.  For example if axis=0, I want to calculate psi for each column, therefore psi_values should have a length equal to the number of columns, not the number of rows.

I'm curious if I've correctly identified the issue.

**Comment by harryz7878** [comment]
yes I agree, I had the same issue and figured out that when using 2d arrays as input, 

`psi_values = np.empty(expected.shape[axis])
`should be changed to
`psi_values = np.empty(expected.shape[1-axis])`

**Comment by mwburke** [comment]
Thanks for flagging. Updated in the latest PR
