### ISSUE TITLE
Is calling the output of np.histogram 'percentage' appropriate?

### ISSUE THREAD

**Issue by orbidder** [mwburke/population-stability-index#2]
First of all, thanks so much for publishing this code.

I have a rather minor comment regarding the naming of the following variables, and the associated write ups of this method you have submitted elsewhere.

`expected_percents = np.histogram(expected_array, breakpoints)[0] / len(expected_array)
        actual_percents = np.histogram(actual_array, breakpoints)[0] / len(actual_array)`

np.histogram() outputs the counts in each bin, and you divide by the total count across all bins to get the _proportion_ of the array in each bin. I think the numpy docs describe this as the "value of the probability density function at the bin, normalized such that the integral over the range is 1". To get the percentage you would need to times by 100. It's a small issue, but the reason I raise it is I first learned of this method from your other posts and before seeing this code my implementation used the percentages (rather than the proportions) and my PSI estimates were incorrect. Calling these values the `expected_proportions` etc. might help others avoid making the same mistake as me. The same goes for your posts elsewhere.

Sorry to be so pedantic, but otherwise great job.

**Comment by mwburke** [comment]
Appreciate the feedback. Noted and updated in the code. Will try and get to other writeups at some point
