### ISSUE TITLE
deprecation warning

### ISSUE THREAD

**Issue by tomaszek0** [mwburke/population-stability-index#3]
Currently, the command
 "eg. round (calculate_psi (starting, new, buckets = 10, axis = 1), 5) == eg round (eg sum (df ['PSI']), 5) ”
returns False instead of True. This is followed by the message:
 "DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  psi_value = np.sum(sub_psi(expected_percents[i], actual_percents[i]) for i in range(0, len(expected_percents)))"

**Comment by mwburke** [comment]
Thanks for flagging. Updated so this warning doesn't occur anymore
